%%
% Loads the path generated by the path planner
% and converts to Matlab timeseries to be used
% in the trajectory generation for the quad_rotor
path_data = readmatrix('run2/quad_rotor_path.csv');
path_data(:,1) = -path_data(:,1);
[path_len,~] = size(path_data);
total_time = 107;
time_data = (1:total_time/path_len:total_time);
path_series = timeseries(path_data, time_data);